name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  frontend-tests:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install frontend dependencies
      run: npm install

    - name: Run frontend tests
      run: npm test